#!/bin/bash
# Check if a build combination is excluded
# Usage: ./check-exclusion.sh <extension> <os> <version> <arch> <config_file> [os_versions_file]
# Exit codes: 0 = excluded, 1 = allowed, other nonzero = error
#
# Matching rules live in scripts/exclusions.jq, shared with the build matrix
# generated by the build/tests workflows.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

EXTENSION="${1:-}"
OS="${2:-}"
VERSION="${3:-}"
ARCH="${4:-}"
CONFIG_FILE="${5:-}"
OS_VERSIONS_FILE="${6:-$(dirname "${CONFIG_FILE}")/os-versions.json}"

if [[ -z "${EXTENSION}" || -z "${OS}" || -z "${VERSION}" || -z "${ARCH}" || -z "${CONFIG_FILE}" ]]; then
    echo "Usage: $0 <extension> <os> <version> <arch> <config_file> [os_versions_file]" >&2
    exit 2
fi

if ! command -v jq &> /dev/null; then
    echo "Error: jq is required but not installed." >&2
    exit 2
fi

REASON=$(jq -r -n -L "${SCRIPT_DIR}" \
    --slurpfile os_versions "${OS_VERSIONS_FILE}" \
    --slurpfile extensions "${CONFIG_FILE}" \
    --arg ext "${EXTENSION}" \
    --arg os "${OS}" \
    --arg version "${VERSION}" \
    --arg arch "${ARCH}" \
    'include "exclusions";
     exclusion_reason($os_versions[0]; $extensions[0]; $ext; $os; $version; $arch)')

echo "${REASON}"

if [[ "${REASON}" == "allowed" ]]; then
    exit 1
fi

exit 0
